### ISSUE TITLE
ASE EMT calculator for cheap testing

### ISSUE THREAD

**Issue by Zausinator** [libAtoms/workflow#41]
Hi, 
While working with wfl, I implemented a simple ase.emt calculator for fast computation, which helped me for developing. The changes include an example python script for an iterative training procedure. In case you're interested, I'd happily create a pull request. 

Files affected are:
- wfl/calculators/dft.py

New files are:
- wfl/calculators/emt.py
- examples/EMT_iterative_gap_fit/gap_fit.py
- examples/EMT_iterative_gap_fit/EMT_atoms.xyz
- examples/EMT_iterative_gap_fit/init_md.traj
- examples/EMT_iterative_gap_fit/multistage_gap_params.json

**Comment by bernstei** [comment]
I'll take a look.  My initial question (before looking at anything) is whether there was a particular reason you created `calculators/emt.py` rather than using `calculators/generic.py`?

**Comment by Zausinator** [comment]
I  see your point and I agree with not creating redundant code. While in the python interface you could achieve the same result with the ```calculators/generic.py``` file without too much effort, it seems to me that the cli interface only allows reference calculations via the ```evaluate_dft``` function in the ```calculators/dft.py``` file. Therefore, quick testing of my iterative processes seems much more convenient (also when using python-only) when having this EMT calculator, before replacing the calculator with e.g. ESPRESSO option or ```calculators/espresso.py```.

**Comment by bernstei** [comment]
Yes, it's certainly possible that we don't have a sufficiently expressive CLI interface to `calculators/generic.py` to do what you want.  Would it be helpful to write a cli function that can use arbitrary (non-DFT) calculators?  

The most generally robust way requires a 3-tuple of a constructor, `args`, and `kwargs`.  The latter two can obviously be passed in using JSON, but the first is trickier.  One option is to pass a class name and use `eval`.   Instead of the tuple we could also pass in the name of a python module, e.g. `model` if `model.py` exists in `CWD` or `PYTHONPATH`, that defines a `calculator` symbol.  That wouldn't necessarily work with autoparallelization or remote jobs (because some calculator objects, e.g. native QUIP fortran like GAP, can't be pickled), however.

**Comment by bernstei** [comment]
Do you want to make a PR? One things that I just noticed, which I'm confused by, is why we're discussing the cli interface, since you're using apparently a python script as your top level, not a shell script.  Maybe we need to see your files to understand what's going on,

**Comment by Zausinator** [comment]
Well, after our discussion I realize that a specific EMT calculator and the cli interface to generic.py seem a bit unnecessary. I think 'll recycle my example scripts in my future implementations and share at a later time. Thanks for your time!

**Comment by bernstei** [comment]
Definitely up to you, but I think we would be interested in seeing how you're using the workflow, whenever you want to share those.

**Comment by Zausinator** [comment]
Gladly! I think I will try recreating my EMT example using ```calculators/generic.py``` and then make a PR with just the examples scripts. Potentially those could be useful for people getting to know the code that feel more comfortable in a Python environment.

**Comment by Zausinator** [comment]
So after a brief absence I finally got around to implementing the calculator the way you suggested. Is there still interest in a python-based iterative workflow example script for simple cheap testing? If so I could make a pull request. For me it would definitely be interesting, if just for my own selfish reasons of getting input from you guys!
